Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,8 +1,3 @@
-# Starter pipeline
-# Start with a minimal pipeline that you can customize to build and deploy your code.
-# Add steps that build, run tests, deploy, and more:
-# https://aka.ms/yaml
-
 trigger:
 - develop
 
@@ -31,14 +26,14 @@ steps:
       ls -lrt
   displayName: 'Download FoD JAR'
 
-# - task: Bash@3
-#   inputs:
-#      targetType: 'inline'
-#      script: |
-#          java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD-SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
-#                 status=$?
-#                 echo $status
-#   displayName: 'FOD Code SCAN'             
+- task: Bash@3
+  inputs:
+      targetType: 'inline'
+      script: |
+          java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD-SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
+                 status=$?
+                 echo $status
+  displayName: 'FOD Code SCAN'             
 
 - task: Bash@3
   inputs:
@@ -58,22 +53,17 @@ steps:
              echo "Application Name = $applicationname"
              echo "CRITICAL = $CRITICAL"
              echo "HIGH = $HIGH"
-             if [ $CRITICAL -gt 5 ]
+             if [ $CRITICAL -gt 0 ]
              then
-               echo "##[error]Failing task because number of critical issues are greater than 5"
+               echo "##[error]Failing task because number of critical issues are greater than 0"
                echo $applicationname
                #curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because number of critical issues in FoD SAST are greater than 5 for '$applicationname'"}' $(teams_webhook)
                exit 1
-             elif [ $HIGH -gt 10 ]
+             elif [ $HIGH -gt 0 ]
              then
                echo "##[error]Failing task because number of high issues are greater than 10"
                #curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because number of high issues in FoD SAST are greater than 10 for '$applicationname'"}' $(teams_webhook)
-               #exit 1
-             elif [ $SUM -gt 50 ]
-             then
-               echo "##[error]Failing task because number of total issues are greater than 50"
-               #curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because total number of issues in FoD SAST are greater than 50 for '$applicationname'"}' $(teams_webhook)
-               #exit 1
+               exit 1
              else
                echo "PASSED"
              fi
