Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -26,14 +26,14 @@ steps:
       ls -lrt
   displayName: 'Download FoD JAR'
 
-- task: Bash@3
-  inputs:
-      targetType: 'inline'
-      script: |
-          java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD_SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
-                 status=$?
-                 echo $status
-  displayName: 'FOD Code SCAN'             
+# - task: Bash@3
+#   inputs:
+#       targetType: 'inline'
+#       script: |
+#           java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD_SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
+#                  status=$?
+#                  echo $status
+#   displayName: 'FOD Code SCAN'             
 
 - task: Bash@3
   inputs:
@@ -70,16 +70,46 @@ steps:
   continueOnError: true            
   displayName: 'Security Gating' 
 
-# - task: Bash@3
-#   inputs:
-#     targetType: 'inline'
-#     script: |
-#       auth=$(curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Connection: close' -d 'grant_type=client_credentials&scope=api-tenant&client_id=$(FOD-API-KEY)&client_secret=$(FOD-SECRET)' 'https://api.sandbox.fortify.com/oauth/token')
-#                    tok3n=$( echo "$auth" | jq '.["access_token"]' )
-#                    tok3n="${tok3n:1:-1}"
-#                    scan_details=$(curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/scan-setup')
-#                    assessmenttypeID=$( echo "$scan_details" | jq '.assessmentTypeId')
-#                    entitlementID=$( echo "$scan_details" | jq '.entitlementId')
-#                    echo $assessmenttypeID
-#                    echo $entitlementID
-#                    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} -d '{"startDate": "2022-08-29T11:52:08.980Z", "assessmentTypeId": ${assessmenttypeID}, "entitlementId": ${entitlementID}, "entitlementFrequencyType": "SingleScan", "isRemediationScan": false, "isBundledAssessment": false, "parentAssessmentTypeId": 0, "applyPreviousScanSettings": false, "scanMethodType": "IDE", "scanTool": "string", "scanToolVersion": "string"}' 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/start-scan'
+- task: Bash@3
+  displayName: "Snyk_SCA_Scanning"
+  inputs:
+     targetType: 'inline'
+     script: |
+       echo "----------Download Latest Snyk CLI-----------"
+       curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1159.0/snyk-linux"
+       chmod +x snyk
+       ls -lrt
+       echo "----------Authenticating Snyk-----------"
+       ./snyk auth $(snyk-token)
+       echo "----------Snyk Monitor-----------"
+       ./snyk monitor --all-projects
+       echo "----------Snyk Scanning-----------"
+       ./snyk test --all-projects
+     failOnStderr: true
+- task: Bash@3
+  displayName: "Snyk Security Gating"
+  inputs:
+     targetType: 'inline'
+     script: |    
+       snykCount=$(curl -X GET --header 'Content-Type: application/json' --header 'Authorization: token $(snyk-token)' 'https://api.snyk.io/api/v1/org/3ce8ad2c-4905-476d-a6ca-df1d9605c959/project/16c0781c-9761-400a-b5c9-5a989c1fe8b4')
+       CRITICAL=$(echo "$snykCount" | jq .issueCountsBySeverity.critical )
+       HIGH=$(echo "$snykCount" | jq .issueCountsBySeverity.high )
+       MEDIUM=$(echo "$snykCount" | jq .issueCountsBySeverity.medium )
+       LOW=$(echo "$snykCount" | jq .issueCountsBySeverity.low )
+       echo "CRITICAL = $CRITICAL"
+       echo "HIGH = $HIGH"
+       echo "MEDIUM = $MEDIUM"
+       echo "LOW = $LOW"
+       if [ $CRITICAL -gt 0 ]
+       then
+         #curl -H 'Content-Type: application/json' -d '{"text": "<Application Name> has Critical Issues in Snyk"}' $(teams_webhook)          
+         echo "##[error]Application has critical issues"
+         exit 1
+       elif [ $HIGH -gt 0 ]
+       then
+         #curl -H 'Content-Type: application/json' -d '{"text": "<Application Name> has High Issues in Snyk"}' $(teams_webhook)          
+         echo "##[error]Application has High issues"
+         exit 1
+       else
+         echo "PASSED"
+       fi
